---
# tasks file for ansible_collections/netapp/ontap/roles/na_ontap_vserver_delete
- name: set-facts netapp_hostname,netapp_username & netapp_password
  set_fact:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
  when:
    - ( netapp_hostname is defined ) and ( netapp_hostname | length > 0 )
    - ( netapp_username is defined ) and ( netapp_username | length > 0 )
    - ( netapp_password is defined ) and ( netapp_password | length > 0 )

- name: Delete all volumes for vserver
  na_ontap_volume:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    https: "{{ https }}"
    validate_certs: "{{ validate_certs }}"
    state: absent
    name: "{{ item }}"
    vserver: "{{ vserver_name }}"
  check_mode: "{{ enable_check_mode }}"
  ignore_errors: "{{ ignore_errors | default(omit) }}"
  loop:
    "{{ volumes }}"
  register: results

- name: debug
  debug:
    var: results
  when: debug_level > 2
